Repository herbsjs/buchu, pull requests merged in 2022-01, with the labels that each got.

#59 This is a change to the MIT license link click event from the buchu d…
  README.md
Labels: documentation, released

#61 build(dependencies): update node version, codecov, semantic release
  .eslintrc.json
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push.yml
  package-lock.json
  package.json
Labels: dependencies, severity-major, wip

#62 fix: update gotu and suma dependencies
  package-lock.json
  package.json
Labels: dependencies, severity-minor

#64 refactor(step.js): remove unused parameter
  src/step.js
Labels: enhancement, severity-minor, wip

#68 style(multistepusecase test): removed unused const
  test/usecase/multiStepUsecase.js
Labels: enhancement, severity-nice-to-have
